services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api-gateway-data-net

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - shared-net
      - api-gateway-data-net

networks:
  shared-net:
    external: true
    name: my-shared-network
  api-gateway-data-net:
    internal: true

volumes:
  postgres_data: