openapi: 3.0.3
info:
  title: Orders API
  version: 1.0.0

paths:
  /auth/login:
    $ref: "./users.yaml#/paths/~1auth~1login"
  /auth/register:
    $ref: "./users.yaml#/paths/~1auth~1register"
  /auth/refresh:
    $ref: "./users.yaml#/paths/~1auth~1refresh"

  /api/order:
    $ref: "./orders.yaml#/paths/~1api~1order"

components:
  schemas:
    LoginRequest:
      $ref: "./users.yaml#/components/schemas/LoginRequest"
    AuthTokensResponse:
      $ref: "./users.yaml#/components/schemas/AuthTokensResponse"
    ErrorResponse:
      $ref: "./users.yaml#/components/schemas/ErrorResponse"

    CreateOrderRequest:
      $ref: "./orders.yaml#/components/schemas/CreateOrderRequest"
    OrderResponse:
      $ref: "./orders.yaml#/components/schemas/OrderResponse"
    OrderItem:
      $ref: "./orders.yaml#/components/schemas/OrderItem"