spring:
  application:
    name: inventory-service
  liquibase:
    enabled: true
    change-log:
      classpath:/db.changelog/db.changelog-master.yaml
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB:inventory_service_db}
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"
    driver-class-name: org.postgresql.Driver
grpc:
  server:
    port: 9090
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} traceId=%X{traceId} %msg%n'
server:
  port: 8083
token:
  jwt:
    salt: rNAWe6FZvpNArgaCAyt0099o+IdvTex1vNObQIN/7hw=
api:
  keys:
    inventory-service: abc123def456ghi789jkl012mno345pqr
    order-service: xyz789uvw123rst456opq789mno012klm
    default-service: 1234